# Generated by Django 5.2.1 on 2025-08-26 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('digital360Api', '0001_initial'),
        ('nss_supervisors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedNSSPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghana_card_record', models.CharField(max_length=20, unique=True)),
                ('nss_id', models.CharField(max_length=25)),
                ('full_name', models.CharField(max_length=255)),
                ('batch_year', models.CharField(max_length=10)),
                ('completion_date', models.CharField(max_length=10)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('restored_once', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NSSPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('ghana_card_record', models.CharField(max_length=20)),
                ('nss_id', models.CharField(default='nss_id', max_length=25)),
                ('start_date', models.CharField(max_length=10)),
                ('end_date', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave'), ('completed', 'Completed')], default='active', max_length=20)),
                ('performance', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('satisfactory', 'Satisfactory'), ('needs_improvement', 'Needs Improvement')], max_length=30, null=True)),
                ('assigned_institution', models.CharField(max_length=255)),
                ('department', models.CharField(choices=[('education', 'Education'), ('health', 'Health'), ('agriculture', 'Agriculture'), ('finance', 'Finance'), ('administration', 'Administration'), ('security', 'Security'), ('transport', 'Transport'), ('works_housing', 'Works and Housing'), ('information', 'Information'), ('tourism', 'Tourism')], default='education', max_length=50)),
                ('assigned_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nss_personnel', to='nss_supervisors.supervisor')),
                ('region_of_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_users', to='digital360Api.region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nss_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
