# Generated by Django 5.1.4 on 2025-04-27 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('digital360Api', '0014_remove_nsspersonnel_assigned_supervisor_and_more'),
        ('nss_supervisors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NSSPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('ghana_card_record', models.CharField(max_length=20)),
                ('nss_id', models.CharField(default='nss_id', max_length=25)),
                ('start_date', models.CharField(max_length=10)),
                ('end_date', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('assigned_institution', models.CharField(max_length=255)),
                ('assigned_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nss_personnel', to='nss_supervisors.supervisor')),
                ('region_of_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_users', to='digital360Api.region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nss_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
