# Generated by Django 5.2.1 on 2025-06-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nss_personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsspersonnel',
            name='department',
            field=models.CharField(choices=[('education', 'Education'), ('health', 'Health'), ('agriculture', 'Agriculture'), ('finance', 'Finance'), ('administration', 'Administration'), ('security', 'Security'), ('transport', 'Transport'), ('works_housing', 'Works and Housing'), ('information', 'Information'), ('tourism', 'Tourism')], default='education', max_length=50),
        ),
        migrations.AddField(
            model_name='nsspersonnel',
            name='performance',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('satisfactory', 'Satisfactory'), ('needs_improvement', 'Needs Improvement')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='nsspersonnel',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave'), ('completed', 'Completed')], default='active', max_length=20),
        ),
    ]
