# Generated by Django 5.2.1 on 2025-07-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nss_personnel', '0002_nsspersonnel_department_nsspersonnel_performance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedNSSPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghana_card_record', models.CharField(max_length=20, unique=True)),
                ('nss_id', models.CharField(max_length=25)),
                ('full_name', models.CharField(max_length=255)),
                ('batch_year', models.CharField(max_length=10)),
                ('completion_date', models.CharField(max_length=10)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
