# Generated by Django 5.2.1 on 2025-08-26 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('file_name', models.CharField(default='Untitled', max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('signature_drawing', models.TextField(blank=True, null=True)),
                ('is_signed', models.BooleanField(default=False)),
                ('signed_file', models.FileField(blank=True, null=True, upload_to='signed_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('form_type', models.CharField(choices=[('Monthly', 'Monthly Evaluation'), ('Quarterly', 'Quarterly Evaluation'), ('Annual', 'Annual Evaluation'), ('Project', 'Project Evaluation')], default='Monthly', max_length=20)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_evaluations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
