# Generated by Django 5.1.4 on 2025-04-27 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default='Untitled', max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('signature_drawing', models.TextField(blank=True, null=True)),
                ('is_signed', models.BooleanField(default=False)),
                ('signed_file', models.FileField(blank=True, null=True, upload_to='signed_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
