# Generated by Django 5.2.1 on 2025-06-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadpdf',
            name='form_type',
            field=models.CharField(choices=[('Monthly', 'Monthly Evaluation'), ('Quarterly', 'Quarterly Evaluation'), ('Annual', 'Annual Evaluation'), ('Project', 'Project Evaluation'), ('General', 'General Document')], default='General', max_length=20),
        ),
    ]
