# Generated by Django 5.2.1 on 2025-06-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_uploads', '0002_uploadpdf_form_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadpdf',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
    ]
