# Generated by Django 5.2.1 on 2025-06-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_uploads', '0004_uploadpdf_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadpdf',
            name='form_type',
            field=models.CharField(choices=[('Monthly', 'Monthly Evaluation'), ('Quarterly', 'Quarterly Evaluation'), ('Annual', 'Annual Evaluation'), ('Project', 'Project Evaluation')], default='Monthly', max_length=20),
        ),
    ]
