# Generated by Django 5.2.1 on 2025-06-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_uploads', '0005_alter_uploadpdf_form_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadpdf',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadpdf',
            name='submitted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
