# Generated by Django 5.2.1 on 2025-06-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_uploads', '0006_uploadpdf_due_date_uploadpdf_submitted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadpdf',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
