# Generated by Django 5.2.1 on 2025-07-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_uploads', '0007_uploadpdf_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadpdf',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
