# Generated by Django 5.1.4 on 2025-03-24 13:18

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GhanaCardRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghana_card_number', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(default='Ghanaian', max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Greater Accra', 'Greater Accra'), ('Western', 'Western'), ('Ashanti', 'Ashanti'), ('Eastern', 'Eastern'), ('Central', 'Central'), ('Volta', 'Volta'), ('Northern', 'Northern'), ('Western North', 'Western North'), ('Oti', 'Oti'), ('Ahafo', 'Ahafo'), ('Bono', 'Bono'), ('Bono East', 'Bono East'), ('Upper East', 'Upper East'), ('Upper West', 'Upper West'), ('North East', 'North East')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workplace_name', models.CharField(max_length=255)),
                ('location_address', models.TextField()),
                ('geolocation_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('geolocation_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('user_type', models.CharField(choices=[('nss', 'NSS Personnel'), ('supervisor', 'Supervisor'), ('admin', 'Administrator')], default='nss', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, related_name='myuser_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='myuser_permissions_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(default='be4552', max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NSSPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=20)),
                ('start_date', models.CharField(max_length=10)),
                ('end_date', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('assigned_institution', models.CharField(max_length=255)),
                ('ghana_card_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='digital360Api.ghanacardrecord')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nss_profile', to=settings.AUTH_USER_MODEL)),
                ('region_of_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_users', to='digital360Api.region')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=20)),
                ('assigned_region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='digital360Api.region')),
                ('ghana_card_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='digital360Api.ghanacardrecord')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_profile', to=settings.AUTH_USER_MODEL)),
                ('assigned_workplaces', models.ManyToManyField(related_name='supervisors', to='digital360Api.workplace')),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrator_profile', to=settings.AUTH_USER_MODEL)),
                ('ghana_card_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='digital360Api.ghanacardrecord')),
                ('assigned_supervisors', models.ManyToManyField(related_name='managed_by_admin', to='digital360Api.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('student_id', models.CharField(default='DEFAULT_ID', max_length=20, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('university_name', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('enrollment_year', models.CharField(max_length=255)),
                ('graduation_year', models.CharField(max_length=255)),
                ('ghana_card_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digital360Api.ghanacardrecord')),
            ],
        ),
        migrations.CreateModel(
            name='UploadPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default='Untitled', max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('signature_drawing', models.TextField(blank=True, null=True)),
                ('is_signed', models.BooleanField(default=False)),
                ('signed_file', models.FileField(blank=True, null=True, upload_to='signed_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
