# Generated by Django 5.1.4 on 2025-03-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital360Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='otp_code',
            field=models.CharField(default='46e12b', max_length=6),
        ),
    ]
