# Generated by Django 5.1.4 on 2025-02-10 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital360Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name']},
        ),
    ]
