# Generated by Django 5.2.1 on 2025-08-26 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('digital360Api', '0001_initial'),
        ('nss_admin', '0001_initial'),
        ('nss_personnel', '0001_initial'),
        ('nss_supervisors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghostdetection',
            name='assigned_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nss_admin.administrator'),
        ),
        migrations.AddField(
            model_name='ghostdetection',
            name='nss_personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nss_personnel.nsspersonnel'),
        ),
        migrations.AddField(
            model_name='ghostdetection',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nss_supervisors.supervisor'),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='universityrecord',
            name='ghana_card_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digital360Api.ghanacardrecord'),
        ),
    ]
