# Generated by Django 5.1.4 on 2025-03-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital360Api', '0002_alter_otpverification_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(choices=[('nss', 'NSS Personnel'), ('supervisor', 'Supervisor'), ('admin', 'Administrator')], max_length=10),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='otp_code',
            field=models.CharField(default='7c6945', max_length=6),
        ),
    ]
