# Generated by Django 5.1.4 on 2025-03-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital360Api', '0003_alter_otpverification_otp_code_uploadpdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadpdf',
            name='user',
        ),
        migrations.AddField(
            model_name='uploadpdf',
            name='file_name',
            field=models.CharField(default='Untitled', max_length=30),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='otp_code',
            field=models.CharField(default='239459', max_length=6),
        ),
    ]
