# Generated by Django 5.1.4 on 2025-03-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital360Api', '0003_alter_myuser_user_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supervisor',
            old_name='assigned_workplaces',
            new_name='assigned_workplace',
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='otp_code',
            field=models.CharField(default='dda8c0', max_length=6),
        ),
    ]
