# Generated by Django 5.2.5 on 2025-08-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital360Api', '0003_alter_otpverification_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='otp_code',
            field=models.CharField(default='f6c38e', max_length=6),
        ),
    ]
