# Generated by Django 5.1.4 on 2025-03-17 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital360Api', '0004_remove_uploadpdf_user_uploadpdf_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadpdf',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadpdf',
            name='signature_drawing',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadpdf',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='uploadpdf',
            name='signed_file',
            field=models.FileField(blank=True, null=True, upload_to='signed_docs/'),
        ),
        migrations.AddField(
            model_name='uploadpdf',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='otp_code',
            field=models.CharField(default='f77461', max_length=6),
        ),
    ]
