# Generated by Django 5.2.5 on 2025-08-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital360Api', '0004_alter_otpverification_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghanacardrecord',
            name='ghana_card_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='otp_code',
            field=models.CharField(default='afcffa', max_length=6),
        ),
    ]
