# Generated by Django 5.1.4 on 2025-03-24 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital360Api', '0004_rename_assigned_workplaces_supervisor_assigned_workplace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='otp_code',
            field=models.CharField(default='39d6d7', max_length=6),
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='assigned_workplace',
        ),
        migrations.AddField(
            model_name='supervisor',
            name='assigned_workplace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisors', to='digital360Api.workplace'),
        ),
    ]
