# Generated by Django 5.1.4 on 2025-03-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital360Api', '0004_alter_otpverification_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='otp_code',
            field=models.CharField(default='ee2ec9', max_length=6),
        ),
    ]
