# Generated by Django 5.1.4 on 2025-01-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital360Api', '0004_alter_region_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(choices=[('Greater Accra', 'Greater Accra'), ('Western', 'Western'), ('Ashanti', 'Ashanti'), ('Eastern', 'Eastern'), ('Central', 'Central'), ('Volta', 'Volta'), ('Northern', 'Northern'), ('Western North', 'Western North'), ('Oti', 'Oti'), ('Ahafo', 'Ahafo'), ('Bono', 'Bono'), ('Bono East', 'Bono East'), ('Upper East', 'Upper East'), ('Upper West', 'Upper West'), ('North East', 'North East'), ('Western Region', 'Western Region')], max_length=255),
        ),
    ]
