# Generated by Django 5.1.4 on 2025-03-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital360Api', '0005_uploadpdf_is_signed_uploadpdf_signature_drawing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='otp_code',
            field=models.CharField(default='d49320', max_length=6),
        ),
    ]
