# Generated by Django 5.2.5 on 2025-08-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital360Api', '0005_alter_ghanacardrecord_ghana_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='otp_code',
            field=models.CharField(default='b15458', max_length=6),
        ),
        migrations.AlterField(
            model_name='outgoingnsspersonnel',
            name='ghana_card_id',
            field=models.CharField(help_text='Ghana Card ID to prevent duplicates', max_length=100, unique=True),
        ),
    ]
