# Generated by Django 5.1.4 on 2025-03-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital360Api', '0005_alter_otpverification_otp_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='otp_code',
            field=models.CharField(default='8e65e0', max_length=6),
        ),
    ]
