# Generated by Django 5.1.4 on 2025-04-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital360Api', '0009_alter_nsspersonnel_ghana_card_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='otp_code',
            field=models.CharField(default='2f03e9', max_length=6),
        ),
    ]
