# Generated by Django 5.1.4 on 2025-04-27 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital360Api', '0010_alter_otpverification_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsspersonnel',
            name='assigned_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nss_personnel', to='digital360Api.supervisor'),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='otp_code',
            field=models.CharField(default='096e7f', max_length=6),
        ),
    ]
