# Generated by Django 5.1.4 on 2025-03-18 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital360Api', '0011_alter_otpverification_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='otp_code',
            field=models.CharField(default='71cb98', max_length=6),
        ),
    ]
