# Generated by Django 5.1.4 on 2025-04-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital360Api', '0011_nsspersonnel_assigned_supervisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='otp_code',
            field=models.CharField(default='a1f338', max_length=6),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='ghana_card_record',
            field=models.CharField(max_length=20),
        ),
    ]
