# Generated by Django 5.1.4 on 2025-04-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital360Api', '0012_alter_otpverification_otp_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='ghana_card_record',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='otp_code',
            field=models.CharField(default='0318f6', max_length=6),
        ),
    ]
