# Generated by Django 5.1.4 on 2025-04-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital360Api', '0013_alter_administrator_ghana_card_record_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nsspersonnel',
            name='assigned_supervisor',
        ),
        migrations.RemoveField(
            model_name='nsspersonnel',
            name='region_of_posting',
        ),
        migrations.RemoveField(
            model_name='nsspersonnel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='assigned_region',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='assigned_workplace',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='uploadpdf',
            name='user',
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='otp_code',
            field=models.CharField(default='e633f3', max_length=6),
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
        migrations.DeleteModel(
            name='NSSPersonnel',
        ),
        migrations.DeleteModel(
            name='Supervisor',
        ),
        migrations.DeleteModel(
            name='UploadPDF',
        ),
    ]
