# Generated by Django 5.1.4 on 2025-04-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital360Api', '0014_remove_nsspersonnel_assigned_supervisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='otp_code',
            field=models.CharField(default='87f6cd', max_length=6),
        ),
    ]
