# Generated by Django 5.2.1 on 2025-07-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital360Api', '0031_alter_otpverification_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='otp_code',
            field=models.CharField(default='f83ffc', max_length=6),
        ),
    ]
