# Generated by Django 5.2.1 on 2025-07-10 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital360Api', '0032_alter_otpverification_otp_code'),
        ('nss_admin', '0002_rename_admin_name_administrator_full_name'),
        ('nss_personnel', '0002_nsspersonnel_department_nsspersonnel_performance_and_more'),
        ('nss_supervisors', '0002_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='otp_code',
            field=models.CharField(default='10a8c1', max_length=6),
        ),
        migrations.CreateModel(
            name='GhostDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_flags', models.JSONField()),
                ('severity', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Admin Review'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('false_positive', 'False Positive'), ('disciplinary_action', 'Disciplinary Action Taken')], default='pending', max_length=20)),
                ('submission_attempt', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('admin_action_taken', models.TextField(blank=True)),
                ('assigned_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nss_admin.administrator')),
                ('nss_personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nss_personnel.nsspersonnel')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nss_supervisors.supervisor')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
