# Generated by Django 5.2.1 on 2025-07-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital360Api', '0033_alter_otpverification_otp_code_ghostdetection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='otp_code',
            field=models.CharField(default='9f0079', max_length=6),
        ),
    ]
