# Generated by Django 5.2.1 on 2025-07-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital360Api', '0035_ghostdetection_evaluation_form_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingNSSPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghana_card_id', models.CharField(help_text='Ghana Card ID to prevent duplicates', max_length=20, unique=True)),
                ('nss_id', models.CharField(help_text='Original NSS ID', max_length=25)),
                ('full_name', models.CharField(help_text='Full name of personnel', max_length=255)),
                ('service_start_date', models.CharField(help_text='When service started', max_length=10)),
                ('service_end_date', models.CharField(help_text='When service ended', max_length=10)),
                ('region_served', models.CharField(help_text='Region where they served', max_length=100)),
                ('department', models.CharField(help_text='Department they worked in', max_length=50)),
                ('institution_assigned', models.CharField(help_text='Institution they were assigned to', max_length=255)),
                ('supervisor_name', models.CharField(blank=True, help_text='Supervisor during service', max_length=255, null=True)),
                ('performance_rating', models.CharField(blank=True, help_text='Final performance rating', max_length=30, null=True)),
                ('completion_year', models.IntegerField(help_text='Year when service was completed')),
                ('transfer_date', models.DateTimeField(auto_now_add=True, help_text='When transferred to outgoing database')),
                ('transfer_reason', models.CharField(default='evaluation_submitted', help_text='Reason for transfer', max_length=50)),
            ],
            options={
                'verbose_name': 'Outgoing NSS Personnel',
                'verbose_name_plural': 'Outgoing NSS Personnel',
                'ordering': ['-transfer_date'],
            },
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='otp_code',
            field=models.CharField(default='c4d44a', max_length=6),
        ),
    ]
