# Generated by Django 5.1.4 on 2025-05-05 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_uploads', '0001_initial'),
        ('messageApp', '0003_remove_message_attachment_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='file_uploads.uploadpdf'),
        ),
    ]
