# Generated by Django 5.2.1 on 2025-06-16 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageApp', '0007_message_reply_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='message',
            name='forwarded_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_messages', to='messageApp.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_forwarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('inquiry', 'Inquiry'), ('feedback', 'Feedback'), ('report', 'Report')], default='inquiry', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.CreateModel(
            name='UserConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(choices=[('supervisor', 'Supervisor'), ('supervisee', 'Supervisee'), ('admin', 'Admin'), ('peer', 'Peer')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('can_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_as_target', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_as_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'can_message')},
            },
        ),
    ]
