# Generated by Django 5.1.4 on 2025-04-29 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nss_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrator',
            old_name='admin_name',
            new_name='full_name',
        ),
    ]
