# Generated by Django 5.1.4 on 2025-04-27 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('digital360Api', '0014_remove_nsspersonnel_assigned_supervisor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('ghana_card_record', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=20)),
                ('assigned_region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='digital360Api.region')),
                ('assigned_workplace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisors', to='digital360Api.workplace')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
